### ISSUE TITLE
Consider relicensing away from CC0

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-python/Pello#13]
Since Fedora no longer allows CC0 for code, would you consider relicensing this to something permitted. One equivalent option might be [`MIT-0`](https://spdx.org/licenses/MIT-0.html).

**Comment by hroncok** [comment]
Fine by me. @encukou, @hrnciar?

**Comment by hrnciar** [comment]
+1

**Comment by encukou** [comment]
Sure.

**Comment by hroncok** [comment]
See https://github.com/fedora-python/Pello/pull/14

**Comment by hroncok** [comment]
See also https://pagure.io/packaging-committee/c/4431afd0efbdb13a93a51d1f6db1466556719434?branch=master
